### ISSUE TITLE
Structure and syntax of a function

### ISSUE THREAD

**Issue by Shashank979** [jmwolff3/tutoring#1]
Could you explain to me how to write the structure and syntax of a function and how to call upon it?

**Comment by jmwolff3** [comment]
You define a function by giving the keyword `def` and then the function name. You can specify any arguments needed as input parameters. Your function will `return` at the end. You can return nothing, or a variable.

Function definition:
`def functionName(argument1, argument2, optional_argument='optional'):
     v = argument1 + argument2
     print(optional_argument) #print is also a function call
     return v
`

To call the function, you need to use the function name and include any required arguments in the call.
Function Call:
`functionName(1, 2)`
`functionName(1,2, 'optional argument sent')`

**Comment by Shashank979** [comment]
how do you define a function to print another function? like what do you write for the argument that says to print the other function?

**Comment by jmwolff3** [comment]
You want to print the value returned by the function. This can be done in several ways. One way is to use variable assignment and print the variable. For instance:
`
def power(x, y):
     return x**y

z = power(2, 16)
print(z)
`

**Comment by jmwolff3** [comment]
way is to use variable assignment and print the variable. For instance:
