### ISSUE TITLE
returning None

### ISSUE THREAD

**Issue by Shashank979** [jmwolff3/tutoring#11]
**Why does this program not return None:**
def feet_to_inches():
    feet = int(input("Input number of feet: "))
    inches = feet * 12
    print(inches)

**while this program does return None:**
def kinetic_energy_calculator(kilograms, velocity):
    kinetic_energy = kilograms * (velocity ** 2) * 0.5
    print(kinetic_energy)

def kinetic_energy_calculator_input():
    kilograms = float(input("Enter the mass in kilograms of the object: "))
    velocity = float(input("Enter the velocity in meters per second: "))
    print(kinetic_energy_calculator(kilograms, velocity))

**Comment by jmwolff3** [comment]
They both `return` None. If you don't print the return value, it won't print out.
