### ISSUE TITLE
Help on problem from Python book

### ISSUE THREAD

**Issue by Shashank979** [jmwolff3/tutoring#16]
[tester copy.txt](https://github.com/jmwolff3/tutoring/files/2346728/tester.copy.txt)

Why is the above code returning False for is_valid when correct_length, has_uppercase, has_lowercase and has_digit are all True?

*had to convert .py file to .txt file as it wouldnt let me upload a python file

**Comment by jmwolff3** [comment]
What is the scope of the variable `is_valid`

**Comment by jmwolff3** [comment]
Also, what are the scopes of `has_upper_case` and `has_lower_case`

**Comment by Shashank979** [comment]
I think their scopes are all local variables
