### ISSUE TITLE
Recusrive power question 

### ISSUE THREAD

**Issue by Shashank979** [jmwolff3/tutoring#19]
for num in xrange(0,5):
	assert(my_pow(num, 0), 1)
assert(my_pow(4,1/2), 2)

What does ^ do?

**Comment by jmwolff3** [comment]
Sorry, ^ is shorthand for exponents.

**Comment by Shashank979** [comment]
so my_power needs to be able to do exponentation to fractions to?

**Comment by jmwolff3** [comment]
Correct. It might be easier to do the case without first and then think about how fractional exponents work.

**Comment by Shashank979** [comment]
Ok, right now my recursive power solution can do negative and positive exponentation, but not fractions
