### ISSUE TITLE
Subclasses and monsters

### ISSUE THREAD

**Issue by Shashank979** [jmwolff3/tutoring#22]
Would it be a bad idea to make a subclass for each different type of monster, or should I just make a parent monster class, which I then pass in different values to make different monsters.

**Comment by jmwolff3** [comment]
I think it would be a good idea to make each different type of monster a subclass of monster.

**Comment by Shashank979** [comment]
Im having trouble with subclasses of subclasses. I have a class called creatures and then a subclass of that called monsters and then multiple subclasses of monsters such as IceMonster and FireMonster. I don't think my syntax/logic for subclasses of subclasses is right. Could you take a look? 

The files is adventureGameObjects.py

**Comment by jmwolff3** [comment]
So for the init methods in subclasses, you should use super().__init__(parameters). If you call Monster.__init__(), you shouldn't need to call Creature.__init__() in the same function. The Monster.__init__() will take care of that cal if it is needed.

**Comment by jmwolff3** [comment]
Take a look at https://www.python-course.eu/python3_inheritance.php. It will give you a couple examples of how to use the init function.
