### ISSUE TITLE
Finding an object in an array

### ISSUE THREAD

**Issue by MayankHirani** [jmwolff3/tutoring#23]
I am having trouble finding a way to find the location of an object in the array, and using .getPosition() to return it.

**Comment by jmwolff3** [comment]
You could iterate through the array and call getPosition on each object, assuming the class has the method.

**Comment by MayankHirani** [comment]
I am unsure what to do for the .getPosition method because argwhere returns multiple instances of where the object is found in the matrix.

**Comment by jmwolff3** [comment]
Which positions are relevant though?

**Comment by MayankHirani** [comment]
Position of Adventurer, and monsters

**Comment by jmwolff3** [comment]
Can you write your own method that computes which objects are intersecting after movement?

**Comment by MayankHirani** [comment]
Ok. Would the method be for the MovingThings class?

**Comment by jmwolff3** [comment]
Probably would be useful for all objects.
