### ISSUE TITLE
questions on problem 1/wordcount.py

### ISSUE THREAD

**Issue by Shashank979** [jmwolff3/tutoring#3]
What does import string do? Also what is the purpose of the main function and what is it meant to do? is it supposed to do both functions countSingleWords and countAllWords.

**Comment by jmwolff3** [comment]
`import string` gives you access to the [string library](https://docs.python.org/3/library/string.html). This enables you to use all the functions contained in the string library.

The main function is typically the function that runs if you just call python3 script.py. You can use it to call both functions if you desire to.

**Comment by jmwolff3** [comment]
Look into https://www.tutorialspoint.com/python3/python_strings.htm
