### ISSUE TITLE
Which QT library

### ISSUE THREAD

**Issue by Shashank979** [jmwolff3/tutoring#31]
For pong do we use the PyQT library: http://pyqt.sourceforge.net/Docs/PyQt5/
or the QT library: https://www.qt.io/qt-for-python

**Comment by Shashank979** [comment]
Or are they the same thing because site which had tutorial on PyQt5 gave link to https://www.qt.io/qt-for-python which had documentation on a PyQt widget.

**Comment by jmwolff3** [comment]
I believe they are based on the same underlying library, but you should use PyQT.
