### ISSUE TITLE
Multiple Replace Functions

### ISSUE THREAD

**Issue by MayankHirani** [jmwolff3/tutoring#7]
string = "Hello. How are you? Good!"
string.replace(".", " ")
string.replace(",", " ")
string.replace("!", " ")
string.replace(":", " ")
string.replace("?", " ")
After multiple replace functions, it returned the string with all the punctuation instead of replacing them.

**Comment by jmwolff3** [comment]
You need to use variable reassignment. The replace method does as described.

> This method returns a copy of the string with all occurrences of substring old replaced by new.
